import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ja' | 'zh-CN' | 'th' | 'vi' | 'id' | 'es' | 'pt' | 'ru' | 'ar' | 'fr' | 'de' | 'zh-TW';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Language context provider for multi-language support
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
    // Update document direction for RTL languages
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const lookup = (lang: Language, key: string): any => {
    const keys = key.split('.');
    let value: any = translations[lang];
    for (const k of keys) {
      if (value && typeof value === 'object') value = value[k];
      else return undefined;
    }
    return typeof value === 'string' ? value : undefined;
  };

  // 回退链:当前语言 → zh-CN → en → 原始 key
  // 这样未翻译的 key 至少不会显示成 raw "profile.title",而是用最完整的版本(中文)
  const t = (key: string): string => {
    return lookup(language, key)
        || lookup('zh-CN', key)
        || lookup('en', key)
        || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

// Translation data
const translations: Record<Language, any> = {
  'en': {
    common: {
      confirm: 'Confirm',
      cancel: 'Cancel',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      search: 'Search',
      submit: 'Submit',
      back: 'Back',
      next: 'Next',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      warning: 'Warning',
      info: 'Information',
      favorites: 'Favorites',
      settings: 'Settings',
      addedToFavorites: 'Added to Favorites',
      removedFromFavorites: 'Removed from Favorites',
    },
    nav: {
      home: 'Home',
      market: 'Market',
      orders: 'Orders',
      flash: 'Binary Options',
      profile: 'Profile',
    },
    auth: {
      accountHint: 'Username must be 4–20 characters (letters, numbers, underscore, or CJK)',
      passwordHint: 'Password must be 6–32 characters',
      fundPassword: 'Fund Password',
      fundPasswordPlaceholder: 'Enter a 6-digit fund password',
      fundPasswordConfirm: 'Confirm Fund Password',
      fundPasswordConfirmPlaceholder: 'Re-enter the fund password',
      fundPasswordInvalid: 'Fund password must be exactly 6 digits',
      fundPasswordMismatch: 'Fund passwords do not match',
      inviteCodeRequired: 'Invitation code is required',
      errors: {
        accountTaken: 'This username is already registered',
        invalidAccount: 'Username must be 4–20 characters (letters, numbers, underscore, or CJK)',
        invalidPassword: 'Password must be 6–32 characters',
        invalidFundPassword: 'Fund password must be exactly 6 digits',
        accountDisabled: 'This account has been disabled',
        invalidInput: 'Please enter username and password',
        network: 'Network error. Please try again.',
      },
    },
    home: {
      title: 'Crypto Trading',
      featured: 'Featured',
      newListing: 'New Listing',
      hotCrypto: 'Hot Crypto',
      forex: 'Forex',
      commodities: 'Commodities',
      indices: 'Indices',
      viewAll: 'View All',
      totalAssets: 'Total Assets',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
      contactSupport: 'Contact Support',
      security: 'Security',
      quickDeposit: 'Quick Deposit',
      regulatory: 'Regulatory',
      loan: 'Loan',
      carefullySelected: 'CAREFULLY SELECTED FOR YOU',
      spread: 'Spread',
      change: 'Change',
    },
    market: {
      title: 'Market',
      crypto: 'Crypto',
      forex: 'Forex',
      commodities: 'Commodities',
      indices: 'Indices',
      search: 'Search markets...',
      price: 'Price',
      change24h: '24h Change',
      volume: 'Volume',
      marketCap: 'Market Cap',
    },
    trading: {
      buy: 'Buy',
      sell: 'Sell',
      price: 'Price',
      amount: 'Amount',
      total: 'Total',
      leverage: 'Leverage',
      takeProfit: 'Take Profit',
      stopLoss: 'Stop Loss',
      market: 'Market',
      limit: 'Limit',
      openPosition: 'Open Position',
      closePosition: 'Close Position',
      positions: 'Positions',
      orders: 'Orders',
      history: 'History',
      chart: 'Chart',
      orderbook: 'Order Book',
      trades: 'Recent Trades',
      long: 'Long',
      short: 'Short',
      settings: 'Trading Settings',
      confirmOrder: 'Confirm Order',
      confirmOrderDesc: 'Confirm before opening positions',
      confirmClose: 'Confirm Close',
      confirmCloseDesc: 'Confirm before closing positions',
      display: 'Display',
      showBalance: 'Show Balance',
      showBalanceDesc: 'Display balance in app',
      defaultChart: 'Default Chart',
      defaultChartDesc: 'Chart type to show by default',
      candleChart: 'Candle',
      lineChart: 'Line',
      areaChart: 'Area',
      tradingPage: 'Trading Page',
      defaultLeverageDesc: 'Default leverage for new positions',
      orderType: 'Order Type',
      defaultOrderTypeDesc: 'Default order type for new positions',
      direction: 'Direction',
      defaultDirectionDesc: 'Default direction for new positions',
      klineInterval: 'K-line Interval',
      defaultKlineIntervalDesc: 'Default time interval for charts',
      holdingsPage: 'Holdings Page',
      autoRefresh: 'Auto Refresh',
      autoRefreshDesc: 'Auto-refresh holdings data',
      refreshInterval: 'Refresh Interval',
      refreshIntervalDesc: 'Data refresh frequency',
      resetDefaults: 'Reset to Defaults',
      openLong: 'Open Long',
      openShort: 'Open Short',
      cross: 'Cross',
      availableBalance: 'Available Balance',
      selectPeriod: 'Select order period',
      selectReturnRate: 'Select return rate',
      enterAmount: 'Enter order amount',
      submitOrder: 'Submit Order',
      currency: 'Currency',
      qty: 'Qty',
      qtyPlaceholder: 'USDT',
      pricePlaceholder: 'Price',
      maxBuyable: 'Max Buyable',
      estimatedCost: 'Estimated Cost',
      fee: 'Fee',
      searchPlaceholder: 'Search symbol...',
      crypto: 'Crypto',
      cryptoPairs: 'Crypto Pairs',
    },
    orders: {
      title: 'Positions',
      current: 'Current',
      history: 'History',
      all: 'All',
      profit: 'Profit',
      loss: 'Loss',
      symbol: 'Symbol',
      type: 'Type',
      openPrice: 'Open Price',
      currentPrice: 'Current Price',
      profitLoss: 'P&L',
      time: 'Time',
      action: 'Action',
      close: 'Close',
      noPositions: 'No positions',
      filter: 'Filter',
      position: 'Position',
      myOrders: 'My Orders',
      binaryHistory: 'Binary Options History',
      ordersTab: 'Orders',
      binaryOptions: 'Binary Options',
      totalAssets: 'Total Assets (USDT)',
      unrealizedPnl: 'Unrealized P&L',
      marginLevel: 'Margin Level',
      currentPositions: 'Current Positions',
      noActivePositions: 'No active positions',
      pending: 'Pending',
      filled: 'Filled',
      cancelled: 'Cancelled',
      noOrders: 'No orders',
      betAmount: 'Bet Amount',
      payoutRate: 'Payout Rate',
      settlementPrice: 'Settlement Price',
      pendingText: 'Pending',
      noOrdersFound: 'No orders found',
      invalidAmount: 'Please enter an order amount',
      call: 'Call',
      put: 'Put',
      win: 'Win',
      lossResult: 'Loss',
      draw: 'Draw',
      detail: {
        title: 'Order Detail',
        orderId: 'Order ID',
        currency: 'Currency',
        buyPrice: 'Buy Price',
        settlePrice: 'Settlement Price',
        openTime: 'Open Time',
        closeTime: 'Close Time',
        billingTime: 'Billing Time',
        amount: 'Amount',
        status: 'Status',
        profit: 'Profit',
        scale: 'Leverage',
        direction: 'Direction',
        result: 'Result',
        orderTime: 'Order Time',
        period: 'Period',
        returnRate: 'Return Rate',
        settleAmount: 'Settlement Amount',
        copy: 'Copy',
        copied: 'Copied',
      },
      card: {
        orderId: 'Order ID',
        amount: 'Amount',
        profit: 'Profit',
        direction: 'Direction',
        returnRate: 'Return Rate',
        billingTime: 'Billing Time',
        orderTime: 'Order Time',
        copy: 'Copy',
        currency: 'Currency',
      },
      status: {
        pending: 'Pending',
        closed: 'Closed',
        cancelled: 'Cancelled',
      },
    },
    profile: {
      title: 'Profile',
      totalAssets: 'Total Assets',
      balance: 'Balance',
      credit: 'Credit',
      equity: 'Equity',
      frozen: 'Frozen',
      available: 'Available',
      deposit: 'Deposit',
      depositEn: 'Deposit',
      withdraw: 'Withdraw',
      winRate: 'Win Rate',
      trades: 'Trades',
      settings: 'Settings',
      settingsEn: 'Settings',
      security: 'Security Center',
      fundRecords: 'Fund Records',
      viewAll: 'View All',
      highStrength: 'High Strength',
      about: 'About Us',
      messages: 'Site Messages',
      contactSupport: 'Click Here Contact Our Online Service',
      logout: 'Logout',
      switchAccount: 'Switch Account / Login',
      vip: 'VIP',
      uid: 'UID',
      notLoggedIn: 'Not logged in',
      confirmLogout: 'Are you sure you want to logout?',
    },
    regulatory: {
      title: 'Regulatory Information',
      subtitle: 'Regulated by international authorities',
      heroTitle: 'Secure and Trustworthy Trading Platform',
      heroDescription: 'We are committed to providing secure, transparent, and compliant cryptocurrency trading services to users worldwide. The platform is strictly regulated by financial regulatory authorities in multiple countries and regions, ensuring your fund security and fair trading.',
      regulatoryInfo: 'Regulatory Information',
      license: 'Regulatory License',
      licenseDesc: 'The platform holds financial regulatory licenses from multiple countries, including compliance certifications from the United States, United Kingdom, Australia, and other countries and regions.',
      compliance: 'Compliance Certification',
      complianceDesc: 'Passed strict audits by international authoritative institutions, ensuring the legality and transparency of platform operations.',
      fundSafety: 'Fund Safety',
      fundSafetyDesc: 'User funds are kept in independent bank accounts, completely separated from company operating funds, ensuring fund safety.',
      industryHonor: 'Industry Honors',
      industryHonorDesc: 'Winner of multiple international fintech awards, recognized as a quality trading platform in the industry.',
      latestNews: 'Latest News',
      news: 'News',
      needHelp: 'Need Help?',
      helpDesc: 'If you have any questions or need more regulatory information, please contact our customer service team.',
      contactSupport: 'Contact Support',
      detail1: 'FCA (Financial Conduct Authority UK)',
      detail2: 'ASIC (Australian Securities and Investments Commission)',
      detail3: 'CySEC (Cyprus Securities and Exchange Commission)',
      detail4: 'ISO 27001 Information Security Management Certification',
      detail5: 'PCI DSS Payment Card Industry Data Security Standard',
      detail6: 'SOC 2 Type II Security Audit Certification',
      detail7: 'Segregated Client Funds',
      detail8: 'Third-party Custodian Bank Supervision',
      detail9: 'Regular Financial Audit Reports',
      detail10: '2024 Best Cryptocurrency Trading Platform',
      detail11: '2023 Financial Technology Innovation Award',
      detail12: 'Five-Star User Satisfaction Rating',
      newsTitle1: 'Platform Obtains Singapore Digital Payment License',
      newsSummary1: 'We are pleased to announce that the platform has successfully obtained the digital payment license issued by the Monetary Authority of Singapore (MAS), marking an important step in our compliance journey.',
      newsTitle2: 'Enhanced KYC Authentication for Better Fund Security',
      newsSummary2: 'To better protect user fund security, the platform has fully upgraded its KYC (Know Your Customer) authentication system, adopting advanced technologies such as AI facial recognition.',
      newsTitle3: 'Platform Completes Annual Security Audit with AAA Rating',
      newsSummary3: 'After a comprehensive audit by an international authoritative security institution, the platform has achieved the highest AAA rating in security, stability, and compliance.',
    },
    login: {
      title: 'Welcome Back',
      welcome: 'Welcome',
      subtitle: 'sign in to continue',
      login: 'Login',
      register: 'Register',
      email: 'Email / Username',
      emailPlaceholder: 'Enter email or username',
      password: 'Password',
      passwordPlaceholder: 'Enter password',
      loginButton: 'LOGIN',
      registerButton: 'REGISTER',
      forgotPassword: 'Forgot Password?',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      terms: 'By continuing, you agree to the',
      termsOfService: 'Terms of Service',
    },
    register: {
      title: 'Create Account',
      welcome: 'Welcome',
      subtitle: 'sign in to continue',
      username: 'Username',
      usernamePlaceholder: 'Enter username',
      email: 'Email / Username',
      emailPlaceholder: 'Enter email or username',
      password: 'Password',
      passwordPlaceholder: 'Enter password',
      invitation: 'Invitation (Optional)',
      invitationPlaceholder: 'Invitation code',
      registerButton: 'REGISTER',
      terms: 'By continuing, you agree to the',
      termsOfService: 'Terms of Service',
    },
    settings: {
      title: 'Settings',
      language: 'Language',
      selectLanguage: 'Select Language',
      theme: 'Theme',
      notifications: 'Notifications',
      security: 'Security',
      about: 'About',
      version: 'Version',
      contactSupport: 'Contact Support',
      rateApp: 'Rate App',
      termsOfService: 'Terms of Service',
      privacyPolicy: 'Privacy Policy',
      logout: 'Logout',
      changePassword: 'Change Password',
      twoFactorAuth: 'Two-Factor Authentication',
      preferences: 'Preferences',
      displayCurrency: 'Display Currency',
      priceAlert: 'Price Alert',
    },
    security: {
      title: 'Security Center',
      loginPassword: 'Login Password',
      loginPasswordDesc: 'Used for login',
      tradingPassword: 'Fund Password',
      tradingPasswordDesc: 'Used for withdrawals and important operations',
      twoFactorAuth: 'Two-Factor Authentication',
      twoFactorAuthDesc: 'Extra security layer',
      kyc: 'KYC Verification',
      kycDesc: 'Verify your identity',
      set: 'Set',
      change: 'Change',
      verify: 'Verify',
      verified: 'Verified',
      notSet: 'Not Set',
    },
    deposit: {
      title: 'Deposit',
      selectMethod: 'Select Deposit Method',
      selectCurrency: 'Select Currency',
      selectNetwork: 'Select Network',
      amount: 'Amount',
      amountPlaceholder: 'Enter amount',
      network: 'Network',
      address: 'Deposit Address',
      copyAddress: 'Copy Address',
      copied: 'Copied!',
      minimumDeposit: 'Minimum Deposit',
      depositNow: 'Deposit Now',
      history: 'Deposit Record',
      pending: 'Pending',
      completed: 'Completed',
      failed: 'Failed',
      scanCode: 'Scan Deposit Code',
      txHash: 'Transaction Hash (Required)',
      txHashPlaceholder: 'Enter transaction hash on blockchain',
      sourceAddress: 'Source Address (Optional)',
      sourceAddressPlaceholder: 'Your wallet address',
      submit: 'Submit Deposit',
      minAmountNotice: 'Minimum deposit: 10 USDT',
      networkNotice: 'Please confirm using correct network',
      confirmationNotice: 'Awaiting confirmation',
      supportNotice: 'Contact support if you have any issues',
    },
    withdraw: {
      title: 'Withdraw',
      selectMethod: 'Select Withdrawal Method',
      amount: 'Amount',
      amountPlaceholder: 'Enter amount',
      address: 'Withdrawal Address',
      addressPlaceholder: 'Enter wallet address',
      network: 'Network',
      fee: 'Fee',
      receive: 'Actual Amount Received',
      minimumWithdraw: 'Minimum Withdrawal',
      maximumWithdraw: 'Maximum Withdrawal',
      withdrawNow: 'Withdraw Now',
      history: 'Withdrawal Record',
      available: 'Available Balance',
      all: 'All',
      submit: 'Confirm Withdrawal',
      minAmountNotice: 'Minimum withdrawal: 20 USDT',
      dailyLimitNotice: 'Daily withdrawal limit: 3 times',
      processingNotice: 'Processing time: Within 24 hours',
      addressNotice: 'Please confirm the withdrawal address is correct, assets cannot be recovered',
      supportNotice: 'Contact support if you have any issues',
    },
    flash: {
      title: 'Flash Contract',
      selectDuration: 'Select Duration',
      seconds: 'seconds',
      minute: 'minute',
      minutes: 'minutes',
      buyUp: 'Buy Up',
      buyDown: 'Buy Down',
      amount: 'Amount',
      currentPrice: 'Current Price',
      estimatedReturn: 'Estimated Return',
      returnRate: 'Return Rate',
      openTrade: 'Open Trade',
      countdown: 'Countdown',
      result: 'Result',
      win: 'Win',
      lose: 'Lose',
      fastTrade: 'Fast Trade',
      fixedReturn: 'Fixed Return',
      quickStart: 'Quick Start',
      maxReturn: 'Max Return',
      variety: 'Variety',
      judgeTrend: 'Judge Trend',
      selectPair: 'Select Trading Pair',
      betRange: 'Bet Range',
      tradeNow: 'Trade Now',
      marketQuote: 'Market Quote',
      features: 'Flash Features',
      pairsAvailable: 'pairs available',
      from30s: 'From 30s',
      upto90: 'Up to 90%',
      easyUnderstand: 'Easy to Understand',
      upDownPrediction: 'Up/Down Prediction',
    },
    depositHistory: {
      title: 'Deposit History',
      all: 'All',
      completed: 'Completed',
      pending: 'Pending',
      failed: 'Failed',
      noRecords: 'No deposit records',
      noDeposit: 'You have not made any deposits yet',
      time: 'Time',
      txHash: 'Transaction Hash',
      statistics: 'Statistics',
      totalCount: 'Total Deposits',
      totalAmount: 'Total Amount',
      method: 'Method',
    },
    fundRecords: {
      title: 'Fund Records',
      all: 'All',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
      completed: 'Completed',
      pending: 'Pending',
      noRecords: 'No fund records',
      recordsWillShow: 'Your transaction records will be displayed here',
      txId: 'Transaction ID',
      currentBalance: 'Current Balance',
      totalIn: 'Total In',
      totalOut: 'Total Withdraw',
      totalOrder: 'Total Order Amount',
      orderTab: 'Orders',
      loadError: 'Failed to load',
      loading: 'Loading...',
      notes: 'Notes',
      balanceAfter: 'Balance',
      types: {
        recharge: 'Admin Recharge',
        deduct:   'Admin Deduction',
        withdraw: 'User Withdraw',
        order:    'Order',
        settle:   'Order Settlement',
        profit:   'Profit Push',
      },
    },
    loginPassword: {
      title: 'Change Login Password',
      oldPassword: 'Old Password',
      oldPasswordPlaceholder: 'Enter old password',
      newPassword: 'New Password',
      newPasswordPlaceholder: 'Enter new password',
      confirmPassword: 'Confirm Password',
      confirmPasswordPlaceholder: 'Enter password again',
      passwordRule: '6-20 characters, including letters and numbers',
      confirmChange: 'Confirm',
      tips: 'Tips:',
      tip1: 'Password must contain letters and numbers',
      tip2: 'Password length should be 6-20 characters',
      tip3: 'Recommend using combination of upper/lowercase letters, numbers and symbols',
      tip4: 'You will need to login again after changing password',
    },
    tradingPassword: {
      title: 'Change Fund Password',
      setTitle: 'Set Fund Password',
      about: 'About Fund Password',
      description: 'Fund password is used for withdrawals and important operations. Please keep it safe.',
      currentPassword: 'Current Fund Password',
      currentPasswordPlaceholder: 'Enter current fund password',
      newPassword: 'New Fund Password',
      password: 'Fund Password',
      passwordPlaceholder: 'Enter 6-digit fund password',
      confirmPassword: 'Confirm Fund Password',
      confirmPasswordPlaceholder: 'Enter fund password again',
      confirmChange: 'Confirm',
      confirmSet: 'Confirm',
      securityTips: 'Security Tips:',
      tip1: 'Fund password must be 6 digits',
      tip2: 'Do not use simple passwords like 123456',
      tip3: 'Fund password cannot be the same as login password',
      tip4: 'Used for withdrawals, transfers and other important operations',
      tip5: 'Contact support to reset if you forget password',
      forgot: 'Forgot fund password?',
    },
    kyc: {
      title: 'KYC Verification',
      status: 'Status: Not Verified',
      statusDescription: 'Complete KYC verification to improve account security and increase withdrawal limit',
      benefits: 'Verification Benefits',
      benefit1: 'Improve account security level',
      benefit2: 'Increase daily withdrawal limit to 100,000 USDT',
      benefit3: 'Enjoy more trading privileges',
      benefit4: 'Priority customer support',
      idType: 'ID Type',
      idCard: 'ID Card',
      passport: 'Passport',
      realName: 'Real Name',
      realNamePlaceholder: 'Enter your real name',
      idNumber: 'ID Number',
      passportNumber: 'Passport Number',
      idNumberPlaceholder: 'Enter ID number',
      passportNumberPlaceholder: 'Enter passport number',
      idFront: 'ID Card Front',
      passportPage: 'Passport Information Page',
      idBack: 'ID Card Back',
      selfie: 'Selfie with ID',
      uploadImage: 'Click to upload image',
      imageFormat: 'Support JPG, PNG format, maximum 5MB',
      takePhoto: 'Take photo',
      selfieDescription: 'Please take selfie while holding your ID',
      submit: 'Submit',
      notice: 'Notice:',
      notice1: 'Ensure uploaded ID photos are clear and complete with readable information',
      notice2: 'Name and ID number must match your ID document',
      notice3: 'Each ID can only verify one account',
      notice4: 'Verification information cannot be modified after submission, please check carefully',
      notice5: 'Review time is approximately 1-3 business days',
      notice6: 'Your information will be strictly confidential',
    },
    language: {
      title: 'Select Language',
      en: 'English',
      ja: '日語',
      'zh-CN': '简体中文',
      th: 'ไทย',
      vi: 'Tiếng Việt',
      id: 'Bahasa Indonesia',
      es: 'Español',
      pt: 'Português',
      ru: 'Русский',
      ar: 'العربية',
      fr: 'Français',
      de: 'Deutsch',
      'zh-TW': '繁體中文',
    },
  },
  'ja': {
    common: {
      confirm: '確認',
      cancel: 'キャンセル',
      save: '保存',
      edit: '編集',
      delete: '削除',
      search: '検索',
      submit: '送信',
      back: '戻る',
      next: '次へ',
      loading: '読み込み中...',
      error: 'エラー',
      success: '成功',
      warning: '警告',
      info: '情報',
      favorites: 'お気に入り',
      settings: '設定',
      addedToFavorites: 'お気���入りに追加しました',
      removedFromFavorites: 'お気に入りから削除しました',
    },
    nav: {
      home: 'ホーム',
      market: 'マーケット',
      orders: '注文',
      flash: 'バイナリーオプション',
      profile: 'プロフィール',
    },
    auth: {
      accountHint: 'アカウントは4〜20文字（英数字・日本語・アンダースコア）',
      passwordHint: 'パスワードは6〜32文字',
      fundPassword: '資金パスワード',
      fundPasswordPlaceholder: '6桁の資金パスワードを入力',
      fundPasswordConfirm: '資金パスワードの確認',
      fundPasswordConfirmPlaceholder: '資金パスワードを再入力',
      fundPasswordInvalid: '資金パスワードは6桁の数字である必要があります',
      fundPasswordMismatch: '資金パスワードが一致しません',
      inviteCodeRequired: '招待コードを入力してください',
      errors: {
        accountTaken: 'このアカウントは既に登録されています',
        invalidAccount: 'アカウントは4〜20文字（英数字・日本語・アンダースコア）',
        invalidPassword: 'パスワードは6〜32文字',
        invalidFundPassword: '資金パスワードは6桁の数字である必要があります',
        accountDisabled: 'アカウントが無効化されています',
        invalidInput: 'アカウントとパスワードを入力してください',
        network: 'ネットワークエラーです。後でもう一度お試しください',
      },
    },
    home: {
      title: '暗号資産取引',
      featured: '注目',
      newListing: '新規上場',
      hotCrypto: '人気暗号資産',
      forex: '外国為替',
      commodities: '商品',
      indices: '指数',
      viewAll: 'すべて表示',
      totalAssets: '総資産',
      deposit: '入金',
      withdraw: '出金',
      contactSupport: 'サポートに連絡',
      security: 'セキュリティ',
      quickDeposit: 'クイックデポジット',
      regulatory: '規制',
      loan: 'ローン',
      carefullySelected: 'あなた専用に慎重に選択',
    },
    market: {
      title: 'マーケット',
      crypto: '暗号資産',
      forex: '外国為替',
      commodities: '商品',
      indices: '指数',
      search: 'マーケットを検索...',
      price: '価格',
      change24h: '24時間変動',
      volume: '取引量',
      marketCap: '時価総額',
    },
    trading: {
      buy: '買い',
      sell: '売り',
      price: '価格',
      amount: '数量',
      total: '合計',
      leverage: 'レバレッジ',
      takeProfit: '利益確定',
      stopLoss: '損切り',
      market: '成行',
      limit: '指値',
      openPosition: 'ポジション開設',
      closePosition: 'ポジション決済',
      positions: 'ポジション',
      orders: '注文',
      history: '履歴',
      chart: 'チャート',
      orderbook: '注文板',
      trades: '最近の取引',
      long: '買い',
      short: '売り',
      settings: '取引設定',
      confirmOrder: '注文確認',
      confirmOrderDesc: 'ポジション開設前に確認',
      confirmClose: '決済確認',
      confirmCloseDesc: 'ポジション決済前に確認',
      display: '表示',
      showBalance: '残高表示',
      showBalanceDesc: 'アプリ内で残高を表示',
      defaultChart: 'デフォルトチャート',
      defaultChartDesc: 'デフォルトで表示するチャートタイプ',
      candleChart: 'ローソク足',
      lineChart: 'ライン',
      areaChart: 'エリア',
      tradingPage: '取引ページ',
      defaultLeverageDesc: '新規ポジションのデフォルトレバレッジ',
      orderType: '注文タイプ',
      defaultOrderTypeDesc: '新規ポジションのデフォルト注文タイプ',
      direction: '方向',
      defaultDirectionDesc: '新規ポジションのデフォルト方向',
      klineInterval: 'K線周期',
      defaultKlineIntervalDesc: 'チャートのデフォルト時間間隔',
      holdingsPage: '保有ページ',
      autoRefresh: '自動更新',
      autoRefreshDesc: '保有データの自動更新',
      refreshInterval: '更新間隔',
      refreshIntervalDesc: 'データ更新頻度',
      resetDefaults: 'デフォルトに戻す',
      openLong: '買い',
      openShort: '売り',
      cross: 'クロス',
      availableBalance: '利用可能残高',
      selectPeriod: '注文期間を選択',
      selectReturnRate: '收益率を選択',
      enterAmount: '注文金額を入力',
      submitOrder: '注文を送信',
      currency: '通貨',
      qty: '数量',
      qtyPlaceholder: 'USDT',
      pricePlaceholder: '価格',
      maxBuyable: '最大購入可能',
      estimatedCost: '予想コスト',
      fee: '手数料',
      searchPlaceholder: 'シンボルを検索...',
      crypto: 'クリプト',
      cryptoPairs: '暗号通貨ペア',
    },
    orders: {
      title: 'ポジション',
      current: '現在',
      history: '履歴',
      all: 'すべて',
      profit: '利益',
      loss: '損失',
      symbol: 'シンボル',
      type: 'タイプ',
      openPrice: '開始価格',
      currentPrice: '現在価格',
      profitLoss: '損益',
      time: '時間',
      action: '操作',
      close: '決済',
      noPositions: 'ポジションなし',
      filter: 'フィルター',
      position: 'ポジション',
      myOrders: 'マイオーダー',
      binaryHistory: 'バイナリーオプション履歴',
      ordersTab: '注文',
      binaryOptions: 'バイナリーオプション',
      totalAssets: '総資産 (USDT)',
      unrealizedPnl: '未実現損益',
      marginLevel: '証拠金レベル',
      currentPositions: '現在のポジション',
      noActivePositions: 'アクティブなポジションはありません',
      pending: '保留中',
      filled: '約定済み',
      cancelled: 'キャンセル済み',
      noOrders: '注文なし',
      betAmount: 'ベット金額',
      payoutRate: 'ペイアウト率',
      settlementPrice: '決済価格',
      pendingText: '保留中',
      noOrdersFound: '注文が見つかりません',
      invalidAmount: '注文金額を入力してください',
      call: 'コール',
      put: 'プット',
      win: '勝ち',
      lossResult: '負け',
      draw: '引き分け',
      detail: {
        title: '注文詳細',
        orderId: '注文ID',
        currency: '通貨',
        buyPrice: '購入価格',
        settlePrice: '決済価格',
        openTime: '開始時間',
        closeTime: '終了時間',
        billingTime: '決済時間',
        amount: '金額',
        status: 'ステータス',
        profit: '損益',
        scale: 'レバレッジ',
        direction: '方向',
        result: '結果',
        orderTime: '注文時間',
        period: '周期',
        returnRate: '収益率',
        settleAmount: '決済金額',
        copy: 'コピー',
        copied: 'コピー済み',
      },
      card: {
        orderId: '注文ID',
        amount: '金額',
        profit: '損益',
        direction: '方向',
        returnRate: '收益率',
        billingTime: '決済時間',
        orderTime: '注文時間',
        copy: 'コピー',
        currency: '通貨',
      },
      status: {
        pending: '保留中',
        closed: '終了',
        cancelled: 'キャンセル',
      },
    },
    profile: {
      title: 'プロフィール',
      totalAssets: '総資産',
      balance: '残高',
      credit: 'クレジット',
      equity: 'クイティ',
      frozen: '凍結',
      available: '利用可能残高',
      deposit: '入金',
      withdraw: '出金',
      winRate: '勝率',
      trades: '取引数',
      settings: '設定',
      security: 'セキュリティセンター',
      fundRecords: '資金記録',
      about: '会社について',
      messages: 'サイトメッセージ',
      contactSupport: 'ここをクリックしてお問い合わせ(オンラインサービス)',
      logout: 'ログアウト',
      switchAccount: 'アカウント切替 / ログイン',
      vip: 'VIP',
      uid: 'UID',
    },
    regulatory: {
      title: '規制情報',
      subtitle: '国際機関の規制を受けています',
      heroTitle: '安全で信頼できる取引プラットフォーム',
      heroDescription: '世界中のユーザーに安全で透明性が高く、準拠した暗号資産取引サービスを提供することに取り組んでいます。当プラットフォームは複数の国と地域の金融規制当局によって厳格に規制されており、お客様の資金の安全性と公正な取引を保証しています。',
      regulatoryInfo: '規制情報',
      license: '規制ライセンス',
      licenseDesc: 'このプラットフォームは、米国、英国、オーストラリアなど複数の国の金融規制ライセンスを保有しており、コンプライアンス認証を受けています。',
      compliance: 'コンプライアンス認証',
      complianceDesc: '国際的な権威ある機関による厳格な監査に合格し、プラットフォーム運営の合法性と透��性を確保しています。',
      fundSafety: '資金の安全性',
      fundSafetyDesc: 'ユーザーの資金は独立した銀行口座に保管され、会社の運営資金とは完全に分離されており、資金の安全性を確保しています。',
      industryHonor: '業界の栄誉',
      industryHonorDesc: '複数の国際的なフィンテック賞を受賞し、業界で認められた優良な取引プラットフォームです。',
      latestNews: '最新ニュース',
      news: 'ニュース',
      needHelp: 'お困りですか？',
      helpDesc: 'ご質問がある場合、または規制情報の詳細については、カスタマーサービスチームにお問い合わせください���',
      contactSupport: 'サポートに連絡',
      detail1: 'FCA（英国金融行為監督機構）',
      detail2: 'ASIC（オーストラリア証券投資委員会）',
      detail3: 'CySEC（キプロス証券取引委員会）',
      detail4: 'ISO 27001情報セキュリティ管理認証',
      detail5: 'PCI DSS決済カード業界データセキュリティ基準',
      detail6: 'SOC 2 Type IIセキュリティ監査認証',
      detail7: '顧客資金の分離管理',
      detail8: 'サードパーティ保管銀行監督',
      detail9: '定期財務監査報告',
      detail10: '2024年最優秀暗号資産取引プラットフォーム',
      detail11: '2023年フィンテック革新賞',
      detail12: 'ユーザー満足度五つ星評価',
      newsTitle1: 'プラットフォームがシンガポールのデジタル決済ライセンスを取得',
      newsSummary1: 'プラットフォームがシンガポール金融管理局（MAS）から発行されたデジタル決済ライセンスの取得に成功したことを発表いたします。これはコンプライアンスの道のりにおける重要な一歩です。',
      newsTitle2: 'KYC認証の強化でより良い資金セキュリティを実現',
      newsSummary2: 'ユーザーの資��セキュリティをより良く保護するため、プラットフォームはKYC（顧客確認）認証システムを全面的にアップグレードし、AI顔認識などの先進技術を採用しています。',
      newsTitle3: 'プラットフォームが年次セキュリティ監査を完了し、AAA評価を獲得',
      newsSummary3: '国際的な権威あるセキュリティ機関による包括的な監査の結果、プラットフォームはセキュリティ、安定性、コンプライアンスの各面で最高のAAA評価を獲得しました。',
    },
    login: {
      title: 'おかえりなさい',
      welcome: 'ようこそ',
      subtitle: '続けるにはサインイン',
      login: 'ログイン',
      register: '登録',
      email: 'メール / ユーザー名',
      emailPlaceholder: 'メールまたはユーザー名を入力',
      password: 'パスワード',
      passwordPlaceholder: 'パスワードを入力',
      loginButton: 'ログイン',
      registerButton: '登録',
      forgotPassword: 'パスワードをお忘れですか？',
      noAccount: 'アカウントをお持ちでないですか？',
      hasAccount: 'すでにアカウントをお持ちですか？',
      terms: '続けることで、以下に同意したものとみなされます',
      termsOfService: '利用規約',
    },
    register: {
      title: 'アカウント作成',
      welcome: 'ようこそ',
      subtitle: '続けるにはサインイン',
      username: 'ユーザー名',
      usernamePlaceholder: 'ユーザー名を入力',
      email: 'メール / ユーザー名',
      emailPlaceholder: 'メールまたはユーザー名を入力',
      password: 'パスワード',
      passwordPlaceholder: 'パスワードを入力',
      invitation: '招待コード（任意）',
      invitationPlaceholder: '招待コード',
      registerButton: '登録',
      terms: '続けることで、以下に同意したものとみなされます',
      termsOfService: '利用規約',
    },
    settings: {
      title: '設定',
      language: '言語',
      selectLanguage: '言語を選択',
      theme: 'テーマ',
      notifications: '通知',
      security: 'セキュリティ',
      about: 'について',
      version: 'バージョン',
      contactSupport: 'サポートに連絡',
      rateApp: 'アプリを評価',
      termsOfService: '利用規約',
      privacyPolicy: 'プライバシーリシー',
      logout: 'ログアウト',
      changePassword: 'パスワード変更',
      twoFactorAuth: '二段階認証',
      preferences: '環境設定',
      displayCurrency: '表示通貨',
      priceAlert: '価格アラート',
    },
    security: {
      title: 'セキ��リティセンター',
      loginPassword: 'ログインパスワード',
      loginPasswordDesc: 'ログインに使用',
      tradingPassword: '資金パスワード',
      tradingPasswordDesc: '出金や重要な操作に使用',
      twoFactorAuth: '二段階認証',
      twoFactorAuthDesc: '追加のセキュリティレイヤー',
      kyc: 'KYC認証',
      kycDesc: '本人確認',
      set: '設定',
      change: '変更',
      verify: '認証',
      verified: '認証済み',
      notSet: '未設定',
    },
    deposit: {
      title: '入金',
      selectMethod: '入金方法を選択',
      amount: '金額',
      amountPlaceholder: '金額を入力',
      network: 'ネットワーク',
      address: 'アドレス',
      copyAddress: 'アドレスをコピー',
      copied: 'コピーしました！',
      minimumDeposit: '最小入金額',
      depositNow: '今すぐ入金',
      history: '入金履歴',
      pending: '保留中',
      completed: '完了',
      failed: '失敗',
    },
    withdraw: {
      title: '出金',
      selectMethod: '出金方を選択',
      amount: '金額',
      amountPlaceholder: '金額を入力',
      address: '出金アドレス',
      addressPlaceholder: 'アドレスを入力',
      network: 'ネットワーク',
      fee: '手数料',
      receive: '受取金額',
      minimumWithdraw: '最小出金額',
      maximumWithdraw: '最大出金額',
      withdrawNow: '今すぐ出金',
      history: '出金履歴',
      available: '利用可能',
      all: 'すべて',
    },
    flash: {
      title: 'フラッシュ契約',
      selectDuration: '期間を選択',
      seconds: '秒',
      minute: '分',
      minutes: '分',
      buyUp: '買い上げ',
      buyDown: '買い下げ',
      amount: '金額',
      currentPrice: '現在価格',
      estimatedReturn: '推定リターン',
      returnRate: '収益率',
      openTrade: '取引開始',
      countdown: 'カウントダウン',
      result: '結果',
      win: '勝利',
      lose: '損失',
      fastTrade: '高速取引',
      fixedReturn: '固定収益',
      quickStart: 'クイックスタート',
      maxReturn: '最大リターン',
      variety: '多様性',
      judgeTrend: 'トレンド判断',
      selectPair: '取引ペアを選択',
      betRange: 'ベット範囲',
      tradeNow: '今すぐ取引',
      marketQuote: '市場相場',
      features: 'フラッシュ機能',
      pairsAvailable: 'ペアが利用可能',
      from30s: '30秒から',
      upto90: '最大90%',
      easyUnderstand: '理解しやすい',
      upDownPrediction: '上下予測',
    },
    language: {
      title: '言語を選択',
      en: 'English',
      ja: '日本語',
      'zh-CN': '简体中文',
      th: 'ไทย',
      vi: 'Tiếng Việt',
      id: 'Bahasa Indonesia',
      es: 'Español',
      pt: 'Português',
      ru: 'Русский',
      ar: 'العربية',
      fr: 'Français',
      de: 'Deutsch',
      'zh-TW': '繁體中文',
    },
  },
  'zh-CN': {
    common: {
      confirm: '确认',
      cancel: '取消',
      save: '保存',
      edit: '编辑',
      delete: '删除',
      search: '搜索',
      submit: '提交',
      back: '返回',
      next: '下一步',
      loading: '加载中...',
      error: '错误',
      success: '成功',
      warning: '警告',
      info: '信息',
      favorites: '收藏',
      settings: '设置',
      addedToFavorites: '已添加到收藏',
      removedFromFavorites: '已从收藏中移除',
    },
    nav: {
      home: '首页',
      market: '行情',
      orders: '订单',
      flash: '期权',
      profile: '我的',
    },
    auth: {
      accountHint: '账号 4-20 位字符,可包含中英文字母、数字、下划线',
      passwordHint: '密码 6-32 位',
      fundPassword: '资金密码',
      fundPasswordPlaceholder: '请输入 6 位数字资金密码',
      fundPasswordConfirm: '确认资金密码',
      fundPasswordConfirmPlaceholder: '请再次输入资金密码',
      fundPasswordInvalid: '资金密码必须为 6 位数字',
      fundPasswordMismatch: '两次资金密码不一致',
      inviteCodeRequired: '请填写邀请码',
      errors: {
        accountTaken: '该账号已被注册',
        invalidAccount: '账号必须是 4-20 位中英数字下划线',
        invalidPassword: '密码长度需 6-32 位',
        invalidFundPassword: '资金密码必须是 6 位数字',
        accountDisabled: '账号已被禁用',
        invalidInput: '请输入账号和密码',
        network: '网络错误,请稍后再试',
      },
    },
    home: {
      title: '加密货币交易',
      featured: '精选',
      newListing: '新币上市',
      hotCrypto: '热门加密货币',
      forex: '外汇',
      commodities: '商品',
      indices: '指数',
      viewAll: '查看全部',
      totalAssets: '总资产',
      deposit: '充值',
      withdraw: '提现',
      contactSupport: '联系支持',
      security: '安全',
      quickDeposit: '快速充值',
      regulatory: '监管',
      loan: '贷款',
      carefullySelected: '为您精心挑选',
      spread: '点差',
      change: '涨幅',
    },
    market: {
      title: '行情',
      crypto: '加密货币',
      forex: '外汇',
      commodities: '商品',
      indices: '指数',
      search: '搜索市场...',
      price: '价格',
      change24h: '24小时涨跌',
      volume: '交量',
      marketCap: '市值',
    },
    trading: {
      buy: '买入',
      sell: '卖出',
      price: '价格',
      amount: '数量',
      total: '总计',
      leverage: '杠杆',
      takeProfit: '止盈',
      stopLoss: '止损',
      market: '市��',
      limit: '限价',
      openPosition: '开仓',
      closePosition: '平仓',
      positions: '持仓',
      orders: '订单',
      history: '历史',
      chart: '图表',
      orderbook: '订单簿',
      trades: '最近成交',
      long: '买涨',
      short: '买跌',
      settings: '交易设置',
      confirmOrder: '确认下单',
      confirmOrderDesc: '开仓前需要确认',
      confirmClose: '确认平仓',
      confirmCloseDesc: '平仓前需要确认',
      display: '显示',
      showBalance: '显示余额',
      showBalanceDesc: '在应用中显示余额',
      defaultChart: '默认图表',
      defaultChartDesc: '默认显示的图表类型',
      candleChart: '蜡烛图',
      lineChart: '折线图',
      areaChart: '面积图',
      tradingPage: '交易页面',
      defaultLeverageDesc: '新仓位的默认杠杆',
      orderType: '订单类型',
      defaultOrderTypeDesc: '新仓位的默认订单类型',
      direction: '方向',
      defaultDirectionDesc: '新仓位的默认方向',
      klineInterval: 'K线周期',
      defaultKlineIntervalDesc: '图表的默认时间间隔',
      holdingsPage: '持仓页面',
      autoRefresh: '自动刷新',
      autoRefreshDesc: '自动刷新持仓数据',
      refreshInterval: '刷新间隔',
      refreshIntervalDesc: '数据刷新频率',
      resetDefaults: '恢复默认设置',
      openLong: '买入开多',
      openShort: '开空',
      cross: '全仓',
      availableBalance: '可用余额',
      selectPeriod: '选择订单周期',
      selectReturnRate: '选择收益率',
      enterAmount: '输入订单金额',
      submitOrder: '提交订单',
      currency: '货币',
      qty: '数量',
      qtyPlaceholder: 'USDT',
      pricePlaceholder: '价格',
      maxBuyable: '最大可买',
      estimatedCost: '预估成本',
      fee: '手续费',
      searchPlaceholder: '搜索交易对...',
      crypto: '加密货币',
      cryptoPairs: '加密货币对',
    },
    orders: {
      title: '持仓',
      current: '当前',
      history: '历史',
      all: '全部',
      profit: '盈利',
      loss: '亏损',
      symbol: '交易对',
      type: '类型',
      openPrice: '开仓价',
      currentPrice: '当前价',
      profitLoss: '盈亏',
      time: '时间',
      action: '操作',
      close: '平仓',
      noPositions: '暂无持仓',
      filter: '筛选',
      position: '持仓',
      myOrders: '我的订单',
      binaryHistory: '期权历史',
      ordersTab: '订单',
      binaryOptions: '期权',
      totalAssets: '总资产 (USDT)',
      unrealizedPnl: '未实现盈亏',
      marginLevel: '保证金率',
      currentPositions: '当前持仓',
      noActivePositions: '暂无活跃持仓',
      pending: '挂单中',
      filled: '已成交',
      cancelled: '��取消',
      noOrders: '暂无订单记录',
      betAmount: '投注金额',
      payoutRate: '赔付率',
      settlementPrice: '结算价',
      pendingText: '待定',
      noOrdersFound: '未找到订单',
      invalidAmount: '请填写订单金额',
      call: '看涨',
      put: '看跌',
      win: '赢',
      lossResult: '输',
      draw: '平',
      detail: {
        title: '订购详情',
        orderId: '订单 ID',
        currency: '币种',
        buyPrice: '买入价',
        settlePrice: '结算价',
        openTime: '开仓时间',
        closeTime: '平仓时间',
        billingTime: '结算时间',
        amount: '金额',
        status: '状态',
        profit: '盈亏',
        scale: '杠杆',
        direction: '方向',
        result: '结果',
        orderTime: '下单时间',
        period: '周期',
        returnRate: '收益率',
        settleAmount: '结算金额',
        copy: '复制',
        copied: '已复制',
      },
      card: {
        orderId: '订单编号',
        amount: '订单金额',
        profit: '利润金额',
        direction: '购买方向',
        returnRate: '收益率',
        billingTime: '计费时间',
        orderTime: '订货时间',
        copy: '复制',
        currency: '货币',
      },
      status: {
        pending: '待结算',
        closed: '已结算',
        cancelled: '已取消',
      },
    },
    profile: {
      title: '我的',
      totalAssets: '总资产',
      balance: '余额',
      credit: '信用',
      equity: '权益',
      frozen: '冻结',
      available: '可用余额',
      deposit: '充值',
      depositEn: 'Deposit',
      withdraw: '提现',
      winRate: '胜率',
      trades: '交易次数',
      settings: '设置',
      settingsEn: 'Settings',
      security: '安全中心',
      fundRecords: '资金记录',
      viewAll: 'View All',
      highStrength: 'High Strength',
      about: '关于公司',
      messages: '站内信',
      contactSupport: '点击此处联系我们(在线客服)',
      logout: '退出',
      switchAccount: '切换账户 / 登录',
      vip: 'VIP',
      uid: 'UID',
      notLoggedIn: '未登录',
      confirmLogout: '确定要退出登录吗?',
    },
    regulatory: {
      title: '监管资讯',
      subtitle: '受国际权威机构监管',
      heroTitle: '安全可信赖的交易平台',
      heroDescription: '我们致力于为全球用户提供安全、透明、合规的加密货币交易服务。平台受到多个国家和地区金融监管机构的严格监管，确保您的资金安全和交易公平。',
      regulatoryInfo: '监管信息',
      license: '监管牌照',
      licenseDesc: '平台持有多国金融监管牌照，包括美国、英国、澳大利亚等多个国家和地区的合规认证。',
      compliance: '合规认证',
      complianceDesc: '通过国际权威机构的严格审核，确保平台运营的合法性和透明度。',
      fundSafety: '资金安全',
      fundSafetyDesc: '用户资金存放于独立的银行账户，与公司运营资金完全隔离，确保资金安全。',
      industryHonor: '行业荣誉',
      industryHonorDesc: '获得多项国际金融科技奖项，是业内公认的优质交易平台。',
      latestNews: '���新资讯',
      news: '新闻',
      needHelp: '需要帮助？',
      helpDesc: '如有任何疑问或需要了解更多监管信息，请联系我们的客服团队。',
      contactSupport: '联系客服',
      detail1: 'FCA (英国金融行为监管局)',
      detail2: 'ASIC (澳大利亚证券投资委员会)',
      detail3: 'CySEC (塞浦路斯证券交易委员会)',
      detail4: 'ISO 27001 信息安全管理认证',
      detail5: 'PCI DSS 支付卡行业数据安全标准',
      detail6: 'SOC 2 Type II 安全审计认证',
      detail7: '客户资金隔离存管',
      detail8: '第三方托管银行监督',
      detail9: '定期财务审计报告',
      detail10: '2024年最佳加密货币交易平台',
      detail11: '2023年金融科技创新奖',
      detail12: '用户满意度五星评级',
      newsTitle1: '平台获得新加坡金融监管局数字支付牌照',
      newsSummary1: '我们很高兴地宣布，平台已成功获得新加坡金融管理局（MAS）颁发的数字支付牌照，这标志着我们在合规化道路上迈出了重要一步。',
      newsTitle2: '加强KYC认证，提升用户资金安全',
      newsSummary2: '为了更好地保护用户资金安全，平台已全面升级KYC（了解你的客户）认证系统，采用AI人脸识别等先进技术。',
      newsTitle3: '平台完成年度安全审计，获得AAA评级',
      newsSummary3: '经过国际权威安全机构的全面审计，平台在安全性、稳定性、合规性等方面均获得AAA最高评级。',
    },
    login: {
      title: '欢迎回来',
      welcome: '欢迎',
      subtitle: '登录以继续',
      login: '登录',
      register: '注册',
      email: '邮箱 / 用户名',
      emailPlaceholder: '请输入邮箱或用户名',
      password: '密码',
      passwordPlaceholder: '请输入密码',
      loginButton: '登录',
      registerButton: '注册',
      forgotPassword: '忘记密码？',
      noAccount: '还没有账户？',
      hasAccount: '已有账户？',
      terms: '继续即表示您同意',
      termsOfService: '服务条款',
    },
    register: {
      title: '创建账户',
      welcome: '欢迎',
      subtitle: '登录以继续',
      username: '用户名',
      usernamePlaceholder: '请输入用户名',
      email: '邮箱 / 用户名',
      emailPlaceholder: '请输入邮箱或用户名',
      password: '密码',
      passwordPlaceholder: '请输入密码',
      invitation: '邀请码（可选）',
      invitationPlaceholder: '邀请码',
      registerButton: '注册',
      terms: '继续即表示您同意',
      termsOfService: '服务条款',
    },
    settings: {
      title: '设置',
      language: '语言',
      selectLanguage: '选择语言',
      theme: '主题',
      notifications: '通知',
      security: '安全',
      about: '关于',
      version: '版本',
      contactSupport: '联系支持',
      rateApp: '评价应用',
      termsOfService: '服务条款',
      privacyPolicy: '隐私政策',
      logout: '退出登录',
      changePassword: '修改密码',
      twoFactorAuth: '双重认证',
      preferences: '偏好设置',
      displayCurrency: '显示货币',
      priceAlert: '价格提醒',
    },
    security: {
      title: '安全中心',
      loginPassword: '登录密码',
      loginPasswordDesc: '用于登录',
      tradingPassword: '资金密码',
      tradingPasswordDesc: '用于提现、重要操作验证',
      twoFactorAuth: '双重认证',
      twoFactorAuthDesc: '额外安全层',
      kyc: 'KYC认证',
      kycDesc: '验证您的身份',
      set: '设置',
      change: '修改',
      verify: '验证',
      verified: '已验证',
      notSet: '未设置',
    },
    deposit: {
      title: '充值',
      selectMethod: '选择充值方式',
      amount: '金额',
      amountPlaceholder: '请输入金额',
      network: '网络',
      address: '地址',
      copyAddress: '复制地址',
      copied: '已复制！',
      minimumDeposit: '最小充值额',
      depositNow: '立即充值',
      history: '充值史',
      pending: '待处理',
      completed: '已完成',
      failed: '失败',
    },
    withdraw: {
      title: '提现',
      selectMethod: '选择提现方式',
      amount: '金额',
      amountPlaceholder: '请输入金额',
      address: '提现地址',
      addressPlaceholder: '请输入地址',
      network: '网络',
      fee: '手续费',
      receive: '实际到账',
      minimumWithdraw: '最小提现额',
      maximumWithdraw: '大提现额',
      withdrawNow: '立即提现',
      history: '提现历史',
      available: '可用余额',
      all: '全部',
    },
    flash: {
      title: '闪约',
      selectDuration: '选择时长',
      seconds: '秒',
      minute: '分钟',
      minutes: '分钟',
      buyUp: '买涨',
      buyDown: '买跌',
      amount: '金额',
      currentPrice: '当前价格',
      estimatedReturn: '预计收益',
      returnRate: '收益率',
      openTrade: '开始交易',
      countdown: '倒计时',
      result: '结果',
      win: '盈利',
      lose: '亏损',
      fastTrade: '快速交易',
      fixedReturn: '固定收益',
      quickStart: '30秒起',
      maxReturn: '最高收益',
      variety: '海量品种',
      judgeTrend: '涨跌判断',
      selectPair: '选择交易品种',
      betRange: '投注范围',
      tradeNow: '立即交易',
      marketQuote: '交易行情',
      features: '秒合约特色',
      pairsAvailable: '个品种',
      from30s: '30秒起',
      upto90: '高达90%',
      easyUnderstand: '简单易懂',
      upDownPrediction: '涨跌预测',
    },
    depositHistory: {
      title: '充值记录',
      all: '全部',
      completed: '已完成',
      pending: '处理中',
      failed: '失败',
      noRecords: '暂无充值记录',
      noDeposit: '您还没有进行过充值',
      time: '时间',
      txHash: '交易哈希',
      statistics: '统计信息',
      totalCount: '总充值次数',
      totalAmount: '总充值金额',
      method: '方式',
    },
    fundRecords: {
      title: '资金记录',
      all: '全部',
      deposit: '充值',
      withdraw: '提现',
      orderTab: '下单记录',
      completed: '已完成',
      pending: '处理中',
      noRecords: '暂无资金记录',
      recordsWillShow: '您的交易记录将显示在这里',
      txId: '交易ID',
      currentBalance: '当前余额',
      totalIn: '总入账',
      totalOut: '总提现',
      totalOrder: '总下单',
      loadError: '加载失败',
      loading: '加载中…',
      notes: '备注',
      balanceAfter: '余额',
      types: {
        recharge: '后台充值',
        deduct:   '后台扣款',
        withdraw: '会员提现',
        order:    '下单',
        settle:   '订单结算',
        profit:   '下推盈利',
      },
    },
    loginPassword: {
      title: '修改登录密码',
      oldPassword: '旧密码',
      oldPasswordPlaceholder: '请输入旧密码',
      newPassword: '新密码',
      newPasswordPlaceholder: '请输入新密码',
      confirmPassword: '确认新密码',
      confirmPasswordPlaceholder: '请再次输入新密码',
      passwordRule: '密码长度为6-20位，包含字母和数字',
      confirmChange: '确认修改',
      tips: '温馨提示：',
      tip1: '密码必须包含字母和数字',
      tip2: '密码长度为6-20位字符',
      tip3: '建议使用大小写字母、数字和符号的组合',
      tip4: '修改密码后需要重新登录',
    },
    tradingPassword: {
      title: '修改资金密码',
      setTitle: '设置资金密码',
      about: '关于资金密码',
      description: '资金密码用于提现和重要操作验证，请妥善保管。',
      currentPassword: '当前资金密码',
      currentPasswordPlaceholder: '请输入当前资金密码',
      newPassword: '新资金密码',
      password: '资金密码',
      passwordPlaceholder: '请输入6位数字资金密码',
      confirmPassword: '确认资金密码',
      confirmPasswordPlaceholder: '请再次输入资金密码',
      confirmChange: '确认修改',
      confirmSet: '确认设置',
      securityTips: '安全提示：',
      tip1: '资金密码必须为6位纯数字',
      tip2: '请勿使用过于简单的密码（如123456）',
      tip3: '资金密码不能与登录密码相同',
      tip4: '用于提现、转账等重要操作验证',
      tip5: '如忘记密码，请联系客服重置',
      forgot: '忘记资金密码？',
    },
    kyc: {
      title: '实名认证',
      status: '认证状态：未认证',
      statusDescription: '完成实名认证后可提高账户安全性和提现额度',
      benefits: '认证权益',
      benefit1: '提高账户安全等级',
      benefit2: '提升每日提现额度至10万USDT',
      benefit3: '享受更多交易特权',
      benefit4: '优先客服支持',
      idType: '证件类型',
      idCard: '身份证',
      passport: '护照',
      realName: '真实姓名',
      realNamePlaceholder: '请输入真实姓名',
      idNumber: '身份证号码',
      passportNumber: '护照号',
      idNumberPlaceholder: '请输入身份证号码',
      passportNumberPlaceholder: '请输入护照号码',
      idFront: '身份证正面',
      passportPage: '护照信息页',
      idBack: '身份证反面',
      selfie: '手持证件照',
      uploadImage: '点击上传图片',
      imageFormat: '支持JPG、PNG格式，大小不超过5MB',
      takePhoto: '拍照上传',
      selfieDescription: '请手持证件与本人合影',
      submit: '提交认证',
      notice: '认证须知：',
      notice1: '请确保上传的证件照片清晰完整，信息可辨识',
      notice2: '姓名和证件号码需与证件保持一致',
      notice3: '每个证件只能认证一个账号',
      notice4: '认证信息提交后无法修改，请仔细核对',
      notice5: '审核时间约1-3个工作日',
      notice6: '您的信息将被严格保密',
    },
    language: {
      title: '选择语言',
      en: 'English',
      ja: '日本語',
      'zh-CN': '简体中文',
      th: 'ไทย',
      vi: 'Tiếng Việt',
      id: 'Bahasa Indonesia',
      es: 'Español',
      pt: 'Português',
      ru: 'Русский',
      ar: 'العربية',
      fr: 'Français',
      de: 'Deutsch',
      'zh-TW': '繁體中文',
    },
  },
  'th': {
    common: {
      confirm: 'ยืนยัน',
      cancel: 'ยกเลิก',
      save: 'บันทึก',
      edit: 'แก้ไข',
      delete: 'ลบ',
      search: 'ค้นหา',
      submit: 'ส่ง',
      back: 'กลับ',
      next: 'ถัดไป',
      loading: 'กำลังโหลด...',
      error: 'ข้อผิดพลาด',
      success: 'สำเร็จ',
      warning: 'คำเตือน',
      info: 'ข้อมูล',
      favorites: 'ราย��ารโปรด',
      settings: 'การตั้งค่า',
      addedToFavorites: 'เพิ่มรายการโปรดแล้ว',
      removedFromFavorites: 'ลบรายการโปรดแล้ว',
    },
    nav: {
      home: 'หน้าแรก',
      market: 'ตลาด',
      orders: 'คำสั่งซื้อ',
      flash: 'ไบนารี่ออปชั่น',
      profile: 'โปรไฟล์',
    },
    home: {
      title: 'การซื้อขายคริปโต',
      featured: 'แนะนำ',
      newListing: 'เหรียญใหม่',
      hotCrypto: 'คริปโตฮิต',
      forex: 'ฟอเร็กซ์',
      commodities: 'สินค้าโภคภัณฑ์',
      indices: 'ดัชนี',
      viewAll: 'ดูทั้งหมด',
      totalAssets: 'สินทรัพย์รวม',
      deposit: 'ฝากเงิน',
      withdraw: 'ถอนเงิน',
      contactSupport: 'ติดต่อฝ่ายสนับสนุน',
      security: 'ความปลอดภัย',
      quickDeposit: 'ฝากเงินเร็ว',
      regulatory: 'การควบคุม',
      loan: 'เงินกู้',
      carefullySelected: 'เลือกมาให้คุณอย่างรอบคอบ',
    },
    market: {
      title: 'ตลาด',
      crypto: 'คริปโต',
      forex: 'ฟอเร็กซ์',
      commodities: 'สินค้าโภคภัณฑ์',
      indices: 'ดัชนี',
      search: 'ค้นหาตลาด...',
      price: 'ราคา',
      change24h: 'เปลี่ยนแปลง 24 ชม.',
      volume: 'ปริมาณ',
      marketCap: 'มูลค่าตลาด',
    },
    trading: {
      buy: 'ซื้อ',
      sell: 'ขาย',
      price: 'ราคา',
      amount: 'จำนวน',
      total: 'ทั้งหมด',
      leverage: 'เลเวอเรจ',
      takeProfit: 'รับกำไร',
      stopLoss: 'หยุดขาดทุน',
      market: 'ตลาด',
      limit: 'จำกัด',
      openPosition: 'เปิดสถานะ',
      closePosition: 'ปิดสถานะ',
      positions: 'สถานะ',
      orders: 'คำสั่ง',
      history: 'ประวัติ',
      chart: 'กราฟ',
      orderbook: 'สมุดคำสั่งซื้อ',
      trades: 'การซื้อขายล่าสุด',
      long: 'ซื้อขึ้น',
      short: 'ซื้อลง',
      settings: 'การตังค่าการซื้อขาย',
      confirmOrder: 'ยืนยั��คำสั่งซื้อ',
      confirmOrderDesc: 'ยืนยันก่อนเปิดสถานะ',
      confirmClose: 'ยืนยันการปิด',
      confirmCloseDesc: 'ยืนยันก่อนปิดสถานะ',
      display: 'การแสดงผล',
      showBalance: 'แสดงยอดคงเหลือ',
      showBalanceDesc: 'แสดงยอดคงเหลือในแอป',
      defaultChart: 'กราฟเริ่มต้น',
      defaultChartDesc: 'ประเภทกราฟที่แสดงโดยค่าเริ่มต้น',
      candleChart: 'แท่งเทียน',
      lineChart: 'เส้น',
      areaChart: 'พื้นที่',
      tradingPage: 'หน้าการซื้อขาย',
      defaultLeverageDesc: 'เลเวอเรจเริ่มต้นสำหรับสถานะใหม่',
      orderType: 'ประเภทคำสั่ง',
      defaultOrderTypeDesc: 'ประเภทคำสั่งเริ่มต้นสำหรับสถานะใหม่',
      direction: 'ทิศทาง',
      defaultDirectionDesc: 'ทิศทางเริ่มต้นสำหรบสถานะใหม่',
      klineInterval: 'ช่วงเวลา K-line',
      defaultKlineIntervalDesc: 'ช่วงเวลาเริ่มต้นสำหรับกราฟ',
      holdingsPage: 'หน้าการถือครอง',
      autoRefresh: 'รีเฟรชอัตโนมัติ',
      autoRefreshDesc: 'รีเฟรชข้อมูลการถือครองอัตโนมัติ',
      refreshInterval: 'ช่วงเวลารีเฟรช',
      refreshIntervalDesc: 'ความถี่ในการรีเฟรชข้อมูล',
      resetDefaults: 'รีเซ็ตเป็นค่าเริ่มต้น',
      openLong: 'เปิดสถานะ Long',
      openShort: 'เปิดสถานะ Short',
      cross: 'ข้าม',
      availableBalance: 'ยอดคงเหลือที่ใช้ได้',
      selectPeriod: 'เลือกระยะเวลาคำสั่งซื้อ',
      selectReturnRate: 'เลือกอัตราผลตอบแทน',
      enterAmount: 'ป้อนจำนวนคำสั่งซื้อ',
      submitOrder: 'ส่งคำสั่งซื้อ',
      currency: 'สกุลเงิน',
      qty: 'จำนวน',
      qtyPlaceholder: 'USDT',
      pricePlaceholder: 'ราคา',
      maxBuyable: 'ซื้อได้สูงสุด',
      estimatedCost: 'ค่าใช้จ่ายโดยประมาณ',
      fee: 'ค่าธรรมเนียม',
      searchPlaceholder: 'ค้นหาสัญลักษณ์...',
      crypto: 'คริปโต',
      cryptoPairs: 'คู่คริปโต',
    },
    orders: {
      title: 'สถานะ',
      current: 'ปัจจุบัน',
      history: 'ประวัติ',
      all: 'ทั้งหมด',
      profit: 'กำไร',
      loss: 'ขาดทุน',
      symbol: 'สัญลักษณ์',
      type: 'ประเภท',
      openPrice: 'ราคาเปิด',
      currentPrice: 'ราคาปัจจุบัน',
      profitLoss: 'กำไร/ขาดทุน',
      time: 'เวลา',
      action: 'การดำเนินการ',
      close: 'ปิด',
      noPositions: 'ไม่มีสถานะ',
      filter: 'กรอง',
      position: 'สถานะ',
      myOrders: 'คำสั่งซื้อของฉัน',
      binaryHistory: 'ประวัติออปชั่นไบนารี',
      ordersTab: 'คำสั่งซื้อ',
      binaryOptions: 'ออปชั่นไบนารี',
      totalAssets: 'สินทรัพย์รวม (USDT)',
      unrealizedPnl: 'กำไรขาดทุนไม่ได้รับ',
      marginLevel: 'ระดับมาร์จิน',
      currentPositions: 'สถานะปัจจุบัน',
      noActivePositions: 'ไม่มีสถานะที่ทำงานอยู่',
      pending: 'รอการดำเนินการ',
      filled: 'ดำเนินการแล้ว',
      cancelled: 'ยกเลิก',
      noOrders: 'ไม่มีคำสั่งซื้อ',
      betAmount: 'จำนวนเดิมพัน',
      payoutRate: 'อัตราการจ่าย',
      settlementPrice: 'ราคาปิดที่กำหนด',
      pendingText: 'รอการดำเนินการ',
      noOrdersFound: 'ไม่พบคำสั่งซื้อ',
      invalidAmount: 'กรุณากรอกจำนวนเงินคำสั่งซื้อ',
      call: 'เรียกซื้อ',
      put: 'เรียกขาย',
      win: 'ชนะ',
      lossResult: 'แพ้',
      draw: 'เสมอ',
      detail: {
        title: 'รายละเอียดคำสั่งซื้อ',
        orderId: 'รหัสคำสั่งซื้อ',
        currency: 'สกุลเงิน',
        buyPrice: 'ราคาซื้อ',
        settlePrice: 'ราคาชำระ',
        openTime: 'เวลาเปิด',
        closeTime: 'เวลาปิด',
        billingTime: 'เวลาชำระ',
        amount: 'จำนวน',
        status: 'สถานะ',
        profit: 'กำไร/ขาดทุน',
        scale: 'เลเวอเรจ',
        direction: 'ทิศทาง',
        result: 'ผลลัพธ์',
        orderTime: 'เวลาสั่งซื้อ',
        period: 'ระยะเวลา',
        returnRate: 'อัตราผลตอบแทน',
        settleAmount: 'จำนวนเงินชำระ',
        copy: 'คัดลอก',
        copied: 'คัดลอกแล้ว',
      },
      card: {
        orderId: 'รหัสคำสั่งซื้อ',
        amount: 'จำนวน',
        profit: 'กำไร/ขาดทุน',
        direction: 'ทิศทาง',
        returnRate: 'อัตราผลตอบแทน',
        billingTime: 'เวลาชำระ',
        orderTime: 'เวลาสั่งซื้อ',
        copy: 'คัดลอก',
        currency: 'สกุลเงิน',
      },
      status: {
        pending: 'รอดำเนินการ',
        closed: 'ปิดแล้ว',
        cancelled: 'ยกเลิก',
      },
    },
    profile: {
      title: 'โปรไฟล์',
      totalAssets: 'สินทรัพย์รวม',
      balance: 'ยอดคงเหลือ',
      credit: 'เครดิต',
      equity: 'ส่วนของผู้ถือหุ้น',
      frozen: 'แช่แข็ง',
      available: 'ยอดคงเหลือที่ใช้ได้',
      deposit: 'ฝากเงิน',
      withdraw: 'ถอนเงิน',
      winRate: 'อัตราชนะ',
      trades: 'จำนวนการซื้อขาย',
      settings: 'การตั้งค่า',
      security: 'ศูนย์ความปลอดภัย',
      fundRecords: 'บันทึกเงินทุน',
      about: 'เกี่ยวกับบริษัท',
      messages: 'ข้อความในเว็บ',
      contactSupport: 'คลิกที่นี่เพื่อติดต่อบริการออนไลน์ของเรา',
      logout: 'ออกจากระบบ',
      switchAccount: 'สลับบัญชี / เข้าสู่ระบบ',
      vip: 'วีไอพี',
      uid: 'UID',
    },
    regulatory: {
      title: 'Regulatory Information',
      subtitle: 'Regulated by international authorities',
      heroTitle: 'Secure and Trustworthy Trading Platform',
      heroDescription: 'We are committed to providing secure, transparent, and compliant cryptocurrency trading services to users worldwide. The platform is strictly regulated by financial regulatory authorities in multiple countries and regions, ensuring your fund security and fair trading.',
      regulatoryInfo: 'Regulatory Information',
      license: 'Regulatory License',
      licenseDesc: 'The platform holds financial regulatory licenses from multiple countries, including compliance certifications from the United States, United Kingdom, Australia, and other countries and regions.',
      compliance: 'Compliance Certification',
      complianceDesc: 'Passed strict audits by international authoritative institutions, ensuring the legality and transparency of platform operations.',
      fundSafety: 'Fund Safety',
      fundSafetyDesc: 'User funds are kept in independent bank accounts, completely separated from company operating funds, ensuring fund safety.',
      industryHonor: 'Industry Honors',
      industryHonorDesc: 'Winner of multiple international fintech awards, recognized as a quality trading platform in the industry.',
      latestNews: 'Latest News',
      news: 'News',
      needHelp: 'Need Help?',
      helpDesc: 'If you have any questions or need more regulatory information, please contact our customer service team.',
      contactSupport: 'Contact Support',
      detail1: 'FCA (Financial Conduct Authority UK)',
      detail2: 'ASIC (Australian Securities and Investments Commission)',
      detail3: 'CySEC (Cyprus Securities and Exchange Commission)',
      detail4: 'ISO 27001 Information Security Management Certification',
      detail5: 'PCI DSS Payment Card Industry Data Security Standard',
      detail6: 'SOC 2 Type II Security Audit Certification',
      detail7: 'Segregated Client Funds',
      detail8: 'Third-party Custodian Bank Supervision',
      detail9: 'Regular Financial Audit Reports',
      detail10: '2024 Best Cryptocurrency Trading Platform',
      detail11: '2023 Financial Technology Innovation Award',
      detail12: 'Five-Star User Satisfaction Rating',
      newsTitle1: 'Platform Obtains Singapore Digital Payment License',
      newsSummary1: 'We are pleased to announce that the platform has successfully obtained the digital payment license issued by the Monetary Authority of Singapore (MAS), marking an important step in our compliance journey.',
      newsTitle2: 'Enhanced KYC Authentication for Better Fund Security',
      newsSummary2: 'To better protect user fund security, the platform has fully upgraded its KYC (Know Your Customer) authentication system, adopting advanced technologies such as AI facial recognition.',
      newsTitle3: 'Platform Completes Annual Security Audit with AAA Rating',
      newsSummary3: 'After a comprehensive audit by an international authoritative security institution, the platform has achieved the highest AAA rating in security, stability, and compliance.',
    },
    login: {
      title: 'ยินดีต้อนรับลับมา',
      welcome: 'ยินดีต้อนรับ',
      subtitle: 'ลงชื่อเข้าใช้เพื่อดำเนินการต่อ',
      login: 'เข้าสู่ระบบ',
      register: 'ล���ทะเบียน',
      email: 'อีเมล / ชื่อผู้ใช้',
      emailPlaceholder: 'กรอกอีเมลหรือชื่อผู้ใช้',
      password: 'รหัสผ่าน',
      passwordPlaceholder: 'กอกรหัสผ่าน',
      loginButton: 'เข้าสู่ระบบ',
      registerButton: 'ลงทะเบียน',
      forgotPassword: 'ลืมรหัสผ่าน?',
      noAccount: 'ยังไฉ่่มีบัญชี?',
      hasAccount: 'มีบัญชีแล้ว?',
      terms: 'เมื่อดำเนินการต่อ คุณยอมรับ',
      termsOfService: 'ข้อกำหนดการให้บริการ',
    },
    register: {
      title: 'สร้างบัญชี',
      welcome: 'ยินดีต้อนรับ',
      subtitle: 'ลงชื่อเข้าใช้เพื่อดำเนินการต่อ',
      username: 'ชื่อผู้ใช้',
      usernamePlaceholder: 'กรอกชื่อผู้ใช้',
      email: 'อีเมล / ชื่อผู้ใช้',
      emailPlaceholder: 'กรอกอีเมลหรือชื่อผู้ใช้',
      password: 'รหัสผ่าน',
      passwordPlaceholder: 'กรอกรหัสผ่าน',
      invitation: 'รหัสเชิญ (ไม่บังคับ)',
      invitationPlaceholder: 'รหัสเชิญ',
      registerButton: 'ลงทะเบียน',
      terms: 'เมื่อดำเนินการต่อ คุณยอรับ',
      termsOfService: 'ข้อกำหนดการให้บริการ',
    },
    settings: {
      title: 'การตั้งค่า',
      language: 'ภาษา',
      selectLanguage: 'เลือกภาษา',
      theme: 'ธีม',
      notifications: 'การแจ้งเตือน',
      security: 'ความปลอดภัย',
      about: 'เกี่ยวกับ',
      version: 'เวอร์ชัน',
      contactSupport: 'ติดต่อฝ่ายสนับสนุน',
      rateApp: 'ให้คะแนนแอป',
      termsOfService: 'ข้อกำหนดการให้บริการ',
      privacyPolicy: 'นโยบายความเป็นส่วนตัว',
      logout: 'ออกจากระบบ',
      changePassword: 'เปลี่ยนรหัสผ่าน',
      twoFactorAuth: 'การยืนยันตัวตนแบบสองปัจจัย',
      preferences: 'การตั้งค่า',
      displayCurrency: 'สกุลเงินที่แสดง',
      priceAlert: 'การแจ้งเตือนราคา',
    },
    security: {
      title: 'ศูนย์ความปลอดภัย',
      loginPassword: 'รหัสผ่านเข้าสู่ระบบ',
      loginPasswordDesc: 'ใช้สำหรับเข้าสู่ระบบ',
      tradingPassword: 'รหัสผ่านกองทุน',
      tradingPasswordDesc: 'ใช้สำหรับการถอนและการดำเนินการที่สำคัญ',
      twoFactorAuth: 'การยืนยันตัวตนแบบสองปัจจัย',
      twoFactorAuthDesc: 'ชั้นความปลอดภัยเพิ่มเติม',
      kyc: 'การยืนยัน KYC',
      kycDesc: 'ยืนยันตัวตนของคุณ',
      set: 'ตั้งค่า',
      change: 'เปลี่ยน',
      verify: 'ยืนยัน',
      verified: 'ยืนยันแล้ว',
      notSet: 'ยังไม่ได้ตั้งค่า',
    },
    deposit: {
      title: 'ฝากเงิน',
      selectMethod: 'เลือกวิีฝากเงิน',
      amount: 'จำนวนเงิน',
      amountPlaceholder: 'กรอกจำนวนเงิน',
      network: 'เครือข่าย',
      address: 'ที่อยู่',
      copyAddress: 'คัดลอกที่อยู่',
      copied: 'คัดลอกแล้ว!',
      minimumDeposit: 'การฝากขั้นต่ำ',
      depositNow: 'ฝากเงินตอนนี้',
      history: 'ประวัติการฝาก',
      pending: 'รอดำเนินการ',
      completed: 'เสร็จสิ้น',
      failed: 'ล้มเหลว',
    },
    withdraw: {
      title: 'ถอนเงิน',
      selectMethod: 'เลือกวิธีถอนเงิน',
      amount: 'จำนวนเงิน',
      amountPlaceholder: 'กรอกจำนวนเงิน',
      address: 'ที่อยู่ถอนเงิน',
      addressPlaceholder: 'กรอกที่อยู่',
      network: 'เครือข่าย',
      fee: 'ค่าธรรมเนียม',
      receive: 'คุณจะได้รับ',
      minimumWithdraw: 'การถอนขั้นต่ำ',
      maximumWithdraw: 'การถอนสูงสุด',
      withdrawNow: 'ถอนเงินตอนนี้',
      history: 'ประวัติการถอน',
      available: 'ที่มีอยู่',
      all: 'ทั้งหมด',
    },
    flash: {
      title: 'แฟลชสัญญา',
      selectDuration: 'เลือกระยะเวลา',
      seconds: 'วินาที',
      minute: 'นาที',
      minutes: 'นาที',
      buyUp: 'ซื้อขึ้น',
      buyDown: 'ซื้อลง',
      amount: 'จำนวน',
      currentPrice: 'ราคาปัจจุบัน',
      estimatedReturn: 'ผลตอบแทนโดยประมาณ',
      returnRate: 'อัตราผลตอบแทน',
      openTrade: 'เปิดการซื้อขาย',
      countdown: 'นับถอยหลัง',
      result: 'ผลลัพธ์',
      win: 'ชนะ',
      lose: 'แพ้',
      fastTrade: 'การซื้อขายอย่างรวดเร็ว',
      fixedReturn: 'ผลตอบแทนคงที่',
      quickStart: 'เริ่มต้นอย่างรวดเร็ว',
      maxReturn: 'ผลตอบแทนสูงสุด',
      variety: 'ความหลากหลาย',
      judgeTrend: 'ตัดสินแนวโน้ม',
      selectPair: 'เลือกคู่เทรด',
      betRange: 'ช่วงเดิมพัน',
      tradeNow: 'เทรดเดี๋ยวนี้',
      marketQuote: 'ราคาตลาด',
      features: 'คุณสมบัติแฟลช',
      pairsAvailable: 'คู่ที่ใช้ได้',
      from30s: 'จาก 30 วินาที',
      upto90: 'สูงสุด 90%',
      easyUnderstand: 'เข้าใจง่าย',
      upDownPrediction: 'ทำนายขึ้น/ลง',
    },
    depositHistory: {
      title: 'ประวัติการฝาก',
      all: 'ทั้งหมด',
      completed: 'เสร็จสิ้น',
      pending: 'รอดำเนินการ',
      failed: 'ล้มเหลว',
      noRecords: 'ไม่มีประวัติการฝาก',
      noDeposit: 'คุณยังไม่ได้ทำการฝากเงิน',
      time: 'เวลา',
      txHash: 'แฮชธุรกรรม',
      statistics: 'สถิติ',
      totalCount: 'จำนวนการฝาก',
      totalAmount: 'จำนวนเงินรวม',
      method: 'วิธีการ',
    },
    fundRecords: {
      title: 'ประวัติการเงิน',
      all: 'ทั้งหมด',
      deposit: 'ฝากเงิน',
      withdraw: 'ถอนเงิน',
      orderTab: 'คำสั่งซื้อ',
      completed: 'เสร็จสิ้น',
      pending: 'รอดำเนินการ',
      noRecords: 'ไม่มีประวัติการเิน',
      recordsWillShow: 'ประวัติการธุรกรมของคุณจะแสดงที่นี่',
      txId: 'รหัสธุรกรรม',
      currentBalance: 'ยอดคงเหลือปัจจุบัน',
      totalIn: 'ยอดฝากรวม',
      totalOut: 'ยอดถอนรวม',
      totalOrder: 'ยอดคำสั่งซื้อรวม',
      loadError: 'โหลดล้มเหลว',
      loading: 'กำลังโหลด...',
      notes: 'หมายเหตุ',
      balanceAfter: 'ยอดคงเหลือ',
      types: {
        recharge: 'เติมเงินโดยแอดมิน',
        deduct:   'หักเงินโดยแอดมิน',
        withdraw: 'ถอนโดยสมาชิก',
        order:    'คำสั่งซื้อ',
        settle:   'การชำระคำสั่งซื้อ',
        profit:   'กำไร',
      },
    },
    loginPassword: {
      title: 'เปลี่ยนรหัสผ่านเข้าสู่ระบบ',
      oldPassword: 'รหัสผ่านเก่า',
      oldPasswordPlaceholder: 'กรอกรหัสผ่านเก่า',
      newPassword: 'รหัสผ่านใหม่',
      newPasswordPlaceholder: 'กรอกรหัสผ่านใหม่',
      confirmPassword: 'ยืนยันรหัสผ่าน',
      confirmPasswordPlaceholder: 'กรอกรหัสผ่านอีกครั้ง',
      passwordRule: '6-20 ตัวอักษร รวมตัวอักษรและตัวเลข',
      confirmChange: 'ยืนยัน',
      tips: 'เคล็ดลับ:',
      tip1: 'รหัสผ่านต้องมีตัวอักษรและตัวเลข',
      tip2: 'ความยาวของรหัสผ่านควรเป็น 6-20 ตัวอักษร',
      tip3: 'แนะนำให้ใช้ความผสมผสาของตัวอักษรพิมพ์ใหญ่/เล็ก ตัวเลขและสัญลักษณ์',
      tip4: 'คุณจะต้องเข้าสู่ระบบอีกครั้งหลังจากเปลี่ยนรหัสผ่าน',
    },
    tradingPassword: {
      title: 'เปลี่ยนรหัสผ่านการซื้อขาย',
      setTitle: 'ตั้งรหัสผ่านการซื้อขาย',
      about: 'เกี่ยวกับรหัสผ่านการซื้อขาย',
      description: 'รหัสผ่านการซื้อขายใช้สำหรับการถอนและดำเนินการสำคัญ โปรดเก็บไว้ดี',
      currentPassword: 'รหัสผ่านการซื้อขายปัจจุบัน',
      currentPasswordPlaceholder: 'กรอกรหัสผ่านการซื้อขายปัจจุบัน',
      newPassword: 'รหัสผ่านการซื้อขายใหม่',
      password: 'รหัสผ่านการซื้อขาย',
      passwordPlaceholder: 'กรอกรหัสผ่านการซื้อขาย 6 หลัก',
      confirmPassword: 'ยืนยันรหัสผ่านการซื้อขาย',
      confirmPasswordPlaceholder: 'กรอกรหัสผ่านการซื้อขายอีกครั้ง',
      confirmChange: 'ยืนยัน',
      confirmSet: 'ยืนัน',
      securityTips: 'เคล็ดลับความปลอดภัย:',
      tip1: 'รหัสผ่านการซื้อขายต้องเป็น 6 หลัก',
      tip2: 'อย่าใช้รหัสผ่านง่ายๆ เช่น 123456',
      tip3: 'รหัสผ่านการซื้อขายไม่สามารถเหมือนกับรหัสผ่านเข้าสู่ระบบได้',
      tip4: 'ใช้สำหรับการถอน โอน และดำเนินการสำคัญอื่นๆ',
      tip5: 'ติดต่อฝ่าย���นับสนุนเพื่อรีเซ็ตรหัสผ่านหากลืม',
      forgot: 'ลืมรหัสผ่านการซื้อขาย?',
    },
    kyc: {
      title: 'การยืนยัน KYC',
      status: 'สถานะ: ยังไม่ได้ยืนยัน',
      statusDescription: 'ดำเนินการยืนยัน KYC เพื่อเพิ่มระดับความปลอดภัยของบัญชีและเพิ่มขีดจำกัดการถอน',
      benefits: 'ประโยชน์ของการยืนยัน',
      benefit1: 'เพิ่มระดับความปลอดภัยขอบัญชี',
      benefit2: 'เพิ่มขีดจำกัดการถอนรายวันเป็น 100,000 USDT',
      benefit3: 'ได้รับสิทธิพิเศษในการซื้อขายมากขึ้น',
      benefit4: 'ได้รับการสนับสนุนลูกค้าด่วน',
      idType: 'ประเภทบัตรประจำตัว',
      idCard: 'บัตรประจำตัวประชาชน',
      passport: 'หนังสือเดินทาง',
      realName: 'ชื่อจริง',
      realNamePlaceholder: 'กรอกชื่อจริงของคุณ',
      idNumber: 'หมายเลขบัตรประจำตัว',
      passportNumber: 'หมายเลขหนังสือเดินทาง',
      idNumberPlaceholder: 'กรอกหมายเลขบัตรประจำตัว',
      passportNumberPlaceholder: 'กรอกหมายเลขหนังสือเดินทาง',
      idFront: 'หน้าบัตรประจำตัว',
      passportPage: 'หน้าข้อมูลหนังสือเดินทาง',
      idBack: 'หลังบัตรประจำตัว',
      selfie: 'ภาพถ่ายตัวเองพร้อมบัตรประจำตัว',
      uploadImage: 'คลิกเพื่ออัปโหลดรูปภาพ',
      imageFormat: 'ร��งรับรูปภาพในรูปแบบ JPG, PNG ขนาดไม่เกิน 5MB',
      takePhoto: 'ถ่ายรูป',
      selfieDescription: 'กรุณาถ่ายรูปตัวเองพร้อมบัตรประจำตัว',
      submit: 'ส่ง',
      notice: 'หมายเหตุ:',
      notice1: 'ตรวจสอบให้แน่ใจว่ารูปภาพบัตรประจำตัวที่อัปโหลดชัดเจนและมีข้อมูลที่สามารถอ่านได้',
      notice2: 'ชื่อและหมายเลขบัตรประจำตัวต้องตรงกับเอกสารบัตรประจำตัวของคุณ',
      notice3: 'แต่ละบัตรประจำตัวสามารถยืนยันเพียงบัญชีเดียวเท่านั้น',
      notice4: 'ข้อมูลกรยืนยันไม่สามารถแก้ไขได้หลังจากส่ง โปรดตรวจสอบให้รอบคอบ',
      notice5: 'เวลาตรวจสอบประมาณ 1-3 วันทำการ',
      notice6: 'ข้อมูลของคุณจะถูกปกปิดอย่างเคร่งครัด',
    },
    language: {
      title: 'เลือกภาษา',
      en: 'English',
      ja: '日本語',
      'zh-CN': '简体中文',
      th: 'ไทย',
      vi: 'Tiếng Việt',
      id: 'Bahasa Indonesia',
      es: 'Español',
      pt: 'Português',
      ru: 'Русский',
      ar: 'العربية',
      fr: 'Français',
      de: 'Deutsch',
      'zh-TW': '繁體中文',
    },
  },
};

// Add remaining translations for es, pt, ru, ar, fr, de, zh-TW by cloning English
translations['es'] = JSON.parse(JSON.stringify(translations['en']));
translations['es'].language = {
  title: 'Seleccionar idioma',
  en: 'English',
  ja: '日本語',
  'zh-CN': '简体中文',
  th: 'ไทย',
  vi: 'Tiếng Việt',
  id: 'Bahasa Indonesia',
  es: 'Español',
  pt: 'Português',
  ru: 'Русский',
  ar: 'العربية',
  fr: 'Français',
  de: 'Deutsch',
  'zh-TW': '繁體中文',
};

translations['pt'] = JSON.parse(JSON.stringify(translations['en']));
translations['pt'].language = translations['es'].language;

translations['ru'] = JSON.parse(JSON.stringify(translations['en']));
translations['ru'].language = translations['es'].language;

translations['ar'] = JSON.parse(JSON.stringify(translations['en']));
translations['ar'].language = translations['es'].language;

translations['fr'] = JSON.parse(JSON.stringify(translations['en']));
translations['fr'].language = translations['es'].language;

translations['de'] = JSON.parse(JSON.stringify(translations['en']));
translations['de'].language = translations['es'].language;

translations['zh-TW'] = JSON.parse(JSON.stringify(translations['zh-CN']));
translations['zh-TW'].language = translations['es'].language;

translations['vi'] = JSON.parse(JSON.stringify(translations['en']));
translations['vi'].language = translations['es'].language;

translations['id'] = JSON.parse(JSON.stringify(translations['en']));
translations['id'].language = translations['es'].language;